# Generated by Django 6.0.6 on 2026-06-15 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitmentApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('department', models.CharField(max_length=100)),
                ('session', models.CharField(max_length=20)),
                ('hall', models.CharField(max_length=100)),
                ('student_id', models.CharField(max_length=50)),
                ('skills', models.TextField(help_text='List your technical/soft skills')),
                ('motivation', models.TextField(help_text='Why do you want to join DUITS?')),
                ('github', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('portfolio', models.URLField(blank=True, null=True)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('payment_response', models.JSONField(blank=True, help_text='Store full AamarPay JSON response', null=True)),
                ('pdf_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecruitmentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_name', models.CharField(help_text='e.g., Spring 2024, Fall 2024', max_length=100)),
                ('is_open', models.BooleanField(default=False)),
                ('application_fee', models.DecimalField(decimal_places=2, default=300.0, max_digits=6)),
                ('deadline', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Recruitment Setting',
                'verbose_name_plural': 'Recruitment Settings',
            },
        ),
    ]
