# Generated by Django 6.0.6 on 2026-06-17 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_recruitmentapplication_recruitment_drive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitmentapplication',
            name='recruitment_drive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='recruitment.recruitmentsettings'),
        ),
    ]
