# Generated by Django 6.0.6 on 2026-06-16 19:37

import payment.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='tracking_id',
            field=models.CharField(blank=True, default=payment.models.generate_32_char_uuid, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(default='aamarPay', max_length=50),
        ),
    ]
