# Generated by Django 6.0.6 on 2026-06-16 19:39

import payment.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_populate_tracking_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='tracking_id',
            field=models.CharField(default=payment.models.generate_32_char_uuid, editable=False, max_length=32, unique=True),
        ),
    ]
