# Generated by Django 6.0.6 on 2026-06-16 19:43

import payment.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_alter_transaction_tracking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='tracking_id',
            field=models.CharField(db_index=True, default=payment.models.generate_32_char_uuid, editable=False, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True),
        ),
    ]
