# Generated by Django 6.0.6 on 2026-06-15 20:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PanelMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(help_text='e.g., President, General Secretary', max_length=100)),
                ('panel_type', models.CharField(choices=[('CURRENT', 'Current Panel'), ('EX', 'Ex Panel')], default='CURRENT', max_length=10)),
                ('session', models.CharField(help_text='e.g., 2023-2024', max_length=50)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first (e.g., 1 for President)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panel_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Panel Member',
                'verbose_name_plural': 'Panel Members',
                'ordering': ['order'],
            },
        ),
    ]
