# api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter

# ==========================================
# 1. IMPORT ALL VIEWSETS
# ==========================================
from article.views import CategoryViewSet, ArticleViewSet
from event.views import EventViewSet
from gallery.views import GalleryImageViewSet
from panel.views import PanelMemberViewSet
from recruitment.views import RecruitmentSettingsViewSet, RecruitmentApplicationViewSet
from analytics.views import SystemLogViewSet
from contact.views import ContactMessageViewSet
from payment.views import PaymentViewSet , TransactionViewSet # <-- NEW PAYMENT IMPORT

# ==========================================
# 2. INITIALIZE THE ROUTER
# ==========================================
router = DefaultRouter()

# ==========================================
# 3. REGISTER ALL ROUTES
# ==========================================
# Content Management
router.register(r'categories', CategoryViewSet, basename='category')
router.register(r'articles', ArticleViewSet, basename='article')
router.register(r'events', EventViewSet, basename='event')
router.register(r'gallery', GalleryImageViewSet, basename='gallery')

# Organization & People
router.register(r'panel-members', PanelMemberViewSet, basename='panelmember')

# Recruitment Process
router.register(r'recruitment-settings', RecruitmentSettingsViewSet, basename='recruitmentsettings')
router.register(r'recruitment-applications', RecruitmentApplicationViewSet, basename='recruitmentapplication')

# Payments
router.register(r'payment', PaymentViewSet, basename='payment') # <-- NEW PAYMENT ROUTE
router.register(r'transactions', TransactionViewSet, basename='transaction')

# Public Operations & Audit
router.register(r'contact', ContactMessageViewSet, basename='contactmessage')
router.register(r'logs', SystemLogViewSet, basename='systemlog')

# ==========================================
# 4. EXPOSE THE URLS
# ==========================================
urlpatterns = [
    # This automatically includes all the standard CRUD routes generated by the router
    path('', include(router.urls)),
]